import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
//import { ThemeProvider } from "@/components/theme-provider";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });
const ThemeProvider = dynamic(() => import('../components/theme-provider'),{ssr:false})

export const metadata: Metadata = {
  title: "Shubham Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
        <Navbar />
        {children}
        </ThemeProvider>
        </body>
    </html>
  );
}
